name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore ./PersonelUygulaması/PersonelUygulaması/PersonelUygulaması.csproj

    - name: Build
      run: dotnet build ./PersonelUygulaması/PersonelUygulaması/PersonelUygulaması.csproj --no-restore

    # Eğer test projesi yoksa bu kısmı silebilirsin
    # - name: Test
    #   run: dotnet test ./PersonelUygulaması/PersonelUygulaması/PersonelUygulaması.csproj --no-build --verbosity normal
