name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore ./PersonnelUygulaması/PersonnelUygulaması.csproj

    - name: Build
      run: dotnet build ./PersonnelUygulaması/PersonnelUygulaması.csproj --no-restore

    - name: Test
      run: dotnet test ./PersonnelUygulaması/PersonnelUygulaması.csproj --no-build --verbosity normal
